services:
  api:
    build:
      context: ${API_BUILD_CONTEXT:-../api}
      target: runner
    environment:
      NODE_ENV: local
      AUTH_EMAIL_VERIFICATION_EXPOSE_DEBUG_CODE: "true"

  api-migrator:
    build:
      context: ${API_BUILD_CONTEXT:-../api}
      target: migrator

  web:
    build:
      context: ${WEB_BUILD_CONTEXT:-../web}
