[global]
type=global
user_agent=Port-Local-Asterisk
endpoint_identifier_order=ip,username

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[livekit-aor]
type=aor
contact=sip:livekit-sip:5060
qualify_frequency=30

[livekit]
type=endpoint
transport=transport-udp
context=from-livekit
disallow=all
allow=ulaw
allow=alaw
aors=livekit-aor
direct_media=no
rtp_symmetric=yes
force_rport=yes

[livekit-identify]
type=identify
endpoint=livekit
match=livekit-sip
