#!/usr/bin/env python3
"""Create private, reusable credentials for the two local SIP test endpoints."""

import json
import os
from pathlib import Path
import secrets


def main():
    os.umask(0o077)
    directory = Path(__file__).resolve().parents[1] / "asterisk" / "local"
    directory.mkdir(parents=True, exist_ok=True)
    credentials_file = directory / "credentials.json"
    if credentials_file.exists():
        credentials = json.loads(credentials_file.read_text())
    else:
        credentials = {number: secrets.token_hex(24) for number in ("1001", "1002")}
        with credentials_file.open("x") as stream:
            json.dump(credentials, stream)
    accounts = []
    for role, number in (("caller", "1001"), ("agent", "1002")):
        password = credentials[number]
        if len(password) != 48 or any(char not in "0123456789abcdef" for char in password):
            raise ValueError(f"Invalid local credential for {number}")
        accounts.append(f"""[{number}]
type=endpoint
transport=transport-udp
context=default
disallow=all
allow=ulaw,alaw
auth={number}-auth
aors={number}
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
dtmf_mode=rfc4733
callerid={role} <{number}>

[{number}-auth]
type=auth
auth_type=userpass
username={number}
password={password}

[{number}]
type=aor
max_contacts=1
remove_existing=yes
qualify_frequency=15
""")
        config = directory / f"{role}.cfg"
        config.write_text(f"""--id=sip:{number}@asterisk
--registrar=sip:asterisk:5060
--proxy=sip:asterisk:5060;lr
--realm=*
--username={number}
--password={password}
--local-port=5060
--rtp-port=4000
--no-tcp
--null-audio
--no-vad
--dis-codec=*
--add-codec=PCMU/8000
--add-codec=PCMA/8000
--use-cli
--log-level=4
--app-log-level=3
""")
        config.chmod(0o600)
    server_config = directory / "pjsip.conf"
    server_config.write_text("; Generated by scripts/pjsua-setup.py\n\n" + "\n".join(accounts))
    server_config.chmod(0o600)
    credentials_file.chmod(0o600)
    print("Local SIP accounts ready: caller=1001, agent=1002 (credentials retained)")


if __name__ == "__main__":
    main()
